# Generated by Django 5.2.6 on 2025-09-30 23:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'verbose_name': 'Capital',
                'verbose_name_plural': 'Capitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('codigo_reserva', models.CharField(max_length=50, unique=True)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('tiempo_vuelo', models.DurationField(blank=True, help_text='Tiempo de vuelo calculado automáticamente', null=True)),
                ('capacidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')])),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(max_length=5)),
                ('pase_abordar', models.FileField(blank=True, null=True, upload_to='pasabordos/')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Maleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.checkin')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Por favor ingresa un correo válido')])),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_completo', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion_facturacion', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20)),
                ('imagen_usuario', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('es_admin', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerolinea.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva', 'Reserva'), ('compra', 'Compra'), ('cancelacion', 'Cancelación'), ('checkin', 'Check-In')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aerolinea.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('num_tiquetes', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.vuelo')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.vuelo'),
        ),
    ]
