# Generated by Django 5.2.6 on 2025-10-01 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ]+$')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ]+$')]),
        ),
    ]
