# Generated by Django 5.2.6 on 2025-10-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0002_remove_usuario_nombre_remove_usuario_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(null=False,blank=False),
        ),
    ]
