# Generated by Django 5.2.6 on 2025-09-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0004_vuelo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion_facturacion',
            field=models.CharField(default='No especificada', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(default='No especificada', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='No especificada', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lugar_nacimiento',
            field=models.CharField(default='No especificada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default='No especificada', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
