# Generated by Django 5.2.6 on 2025-09-29 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0005_remove_usuario_direccion_remove_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'verbose_name': 'Capital',
                'verbose_name_plural': 'Capitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Por favor ingresa un correo válido')]),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='tipo',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=20),
        ),
    ]
