# Generated by Django 5.2.6 on 2025-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0006_add_capital_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='tiempo_vuelo',
            field=models.DurationField(blank=True, help_text='Tiempo de vuelo calculado automáticamente', null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
