# Generated by Django 5.2.6 on 2025-09-29 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0007_add_vuelo_time_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')]),
        ),
    ]
