# Generated by Django 5.2.6 on 2025-10-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0002_departamento_pais_municipio_departamento_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lugar_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerolinea.municipio'),
        ),
    ]
