# Generated by Django 5.2.6 on 2025-10-19 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0003_alter_usuario_lugar_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='lugar_nacimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerolinea.departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerolinea.municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerolinea.pais'),
        ),
    ]
