# Generated by Django 5.2.6 on 2025-10-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0004_remove_usuario_lugar_nacimiento_usuario_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_root',
            field=models.BooleanField(default=False),
        ),
    ]
