# Generated by Django 5.2.6 on 2025-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0005_usuario_es_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registro_completo',
            field=models.BooleanField(default=False),
        ),
    ]
