# Generated by Django 5.2.6 on 2025-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0008_alter_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vuelos/'),
        ),
    ]
