# Generated by Django 5.2.6 on 2025-10-28 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0009_vuelo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='asiento_asignado',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='check_in_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default=0, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('confirmada', 'Confirmada')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_tiquetes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'vuelo'), name='unique_usuario_vuelo'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.usuario'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aerolinea.carrito'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.vuelo'),
        ),
    ]
