# Generated by Django 5.2.6 on 2025-10-28 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0010_carrito_carritoitem_reserva_asiento_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aerolinea.reserva'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('carrito', 'vuelo')},
        ),
    ]
