# Generated by Django 5.2.6 on 2025-10-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0011_carritoitem_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_usuario_vuelo',
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('usuario', 'vuelo'), name='unique_usuario_vuelo_activa'),
        ),
    ]
