# Generated by Django 5.2.6 on 2025-09-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0003_usuario_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='tipo',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], default='NACIONAL', max_length=20),
        ),
    ]
